version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:14-alpine
    container_name: tongpin-postgres
    environment:
      POSTGRES_DB: tongpin_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - tongpin-network
    restart: unless-stopped

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: tongpin-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tongpin-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # MongoDB 文档数据库
  mongodb:
    image: mongo:6-jammy
    container_name: tongpin-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tongpin_chat
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - tongpin-network
    restart: unless-stopped

  # Elasticsearch 搜索引擎
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: tongpin-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - tongpin-network
    restart: unless-stopped

  # 用户服务 (User Service)
  user-service:
    build:
      context: ./backend
      dockerfile: user-service/Dockerfile
    container_name: tongpin-user-service
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: tongpin_db
      DB_USER: postgres
      DB_PASSWORD: password
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-here
      JWT_REFRESH_SECRET: your-refresh-secret-key-here
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    networks:
      - tongpin-network
    restart: unless-stopped
    volumes:
      - ./backend/user-service/src:/app/user-service/src
      - ./backend/user-service/logs:/app/user-service/logs
      - /app/node_modules
    command: pnpm run dev

  # 搭子服务 (Post Service)
  post-service:
    build:
      context: ./backend
      dockerfile: post-service/Dockerfile
    container_name: tongpin-post-service
    environment:
      NODE_ENV: development
      PORT: 3002
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: tongpin_db
      DB_USER: postgres
      DB_PASSWORD: password
      REDIS_URL: redis://redis:6379
      USER_SERVICE_URL: http://user-service:3001
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - redis
      - user-service
    networks:
      - tongpin-network
    restart: unless-stopped
    volumes:
      - ./backend/post-service/src:/app/post-service/src
      - /app/node_modules
    command: pnpm run dev

  # 灵魂服务 (Soul Service)
  soul-service:
    build:
      context: ./backend
      dockerfile: soul-service/Dockerfile
    container_name: tongpin-soul-service
    environment:
      NODE_ENV: development
      PORT: 3004
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: tongpin_db
      DB_USER: postgres
      DB_PASSWORD: password
      REDIS_URL: redis://redis:6379
    ports:
      - "3004:3004"
    depends_on:
      - postgres
      - redis
    networks:
      - tongpin-network
    restart: unless-stopped
    volumes:
      - ./backend/soul-service/src:/app/soul-service/src
      - /app/node_modules
    command: pnpm run dev

  # 推荐服务 (Recommend Service)
  recommend-service:
    build:
      context: ./backend
      dockerfile: recommend-service/Dockerfile
    container_name: tongpin-recommend-service
    environment:
      NODE_ENV: development
      PORT: 3005
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: tongpin_db
      DB_USER: postgres
      DB_PASSWORD: password
      REDIS_URL: redis://redis:6379
    ports:
      - "3005:3005"
    depends_on:
      - postgres
      - redis
    networks:
      - tongpin-network
    restart: unless-stopped
    volumes:
      - ./backend/recommend-service/src:/app/recommend-service/src
      - /app/node_modules
    command: pnpm run dev

  # API 网关 (API Gateway)
  api-gateway:
    build:
      context: ./backend
      dockerfile: api-gateway/Dockerfile
    container_name: tongpin-api-gateway
    environment:
      NODE_ENV: development
      PORT: 3000
      USER_SERVICE_URL: http://user-service:3001
      POST_SERVICE_URL: http://post-service:3002
      SOUL_SERVICE_URL: http://soul-service:3004
      RECOMMEND_SERVICE_URL: http://recommend-service:3005
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - post-service
      - soul-service
      - recommend-service
    networks:
      - tongpin-network
    restart: unless-stopped
    volumes:
      - ./backend/api-gateway/src:/app/api-gateway/src
      - /app/node_modules
    command: pnpm run dev

volumes:
  postgres_data:
  redis_data:
  mongodb_data:
  elasticsearch_data:

networks:
  tongpin-network:
    driver: bridge