packages:
  - 'user-service'
  - 'post-service'
  - 'chat-service'
  - 'soul-service'
  - 'recommend-service'
  - 'api-gateway'

# 共享依赖配置
catalog:
  # 核心依赖
  'express': '^4.18.2'
  'typescript': '^5.2.2'
  'ts-node': '^10.9.1'

  # 数据库相关
  'pg': '^8.11.0'
  'redis': '^4.6.7'
  'mongodb': '^5.9.0'

  # 认证相关
  'jsonwebtoken': '^9.0.2'
  'bcryptjs': '^2.4.3'

  # 工具库
  'cors': '^2.8.5'
  'helmet': '^7.0.0'
  'dotenv': '^16.3.1'
  'winston': '^3.10.0'
  'joi': '^17.9.2'
  'uuid': '^9.0.1'

  # 开发依赖
  '@types/express': '^4.17.21'
  '@types/pg': '^8.10.2'
  '@types/redis': '^4.0.11'
  '@types/jsonwebtoken': '^9.0.3'
  '@types/bcryptjs': '^2.4.4'
  '@types/cors': '^2.8.15'
  '@types/uuid': '^9.0.4'
  '@types/node': '^20.8.2'
  '@types/jest': '^29.5.5'
  'nodemon': '^3.0.1'
  'jest': '^29.7.0'
  'eslint': '^8.50.0'
  'prettier': '^3.0.3'

# pnpm配置
nodeLinker: isolated
enablePnp: false
resolutionMode: highest